# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_resource_test_helper}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flavio Castelli"]
  s.date = %q{2010-05-14}
  s.description = %q{active_resource_test_helper makes it easier to use ActiveResouce::HttpMock.
                      Instead of declaring manually all the request-response pairs,
                      it’s possible to use dynamically generated contents.
                      These contents are defined using factory_girl and are
                      stored into a Redis database using ohm.}
  s.email = %q{flavio@castelli.name}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/active_resource_test_helper.rb",
     "lib/active_resource_test_helper/active_resource/http_mock.rb",
     "lib/active_resource_test_helper/factory.rb",
     "lib/active_resource_test_helper/ohm/model.rb",
     "test/active_resource_factories_test.rb",
     "test/active_resource_http_mock_test.rb",
     "test/active_resource_test_helper_test.rb",
     "test/factories/user_factory.rb",
     "test/ohm_model_changes_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/flavio/active_resource_test_helper}
  s.rdoc_options = ["--line-numbers", "--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ActiveResource test helper.}
  s.test_files = [
    "test/active_resource_test_helper_test.rb",
     "test/ohm_model_changes_test.rb",
     "test/active_resource_factories_test.rb",
     "test/active_resource_http_mock_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<factory_girl>, [">= 1.2.3"])
      s.add_runtime_dependency(%q<redis>, [">= 1.0.4"])
      s.add_runtime_dependency(%q<ohm>, [">= 0.0.35"])
    else
      s.add_dependency(%q<factory_girl>, [">= 1.2.3"])
      s.add_dependency(%q<redis>, [">= 1.0.4"])
      s.add_dependency(%q<ohm>, [">= 0.0.35"])
    end
  else
    s.add_dependency(%q<factory_girl>, [">= 1.2.3"])
    s.add_dependency(%q<redis>, [">= 1.0.4"])
    s.add_dependency(%q<ohm>, [">= 0.0.35"])
  end
end

